# Generated by Django 5.2.1 on 2026-04-03 04:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("VERIFYCODE", "Verifycode"),
                            ("MESSAGE", "Message"),
                            ("REVIEW", "Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("public_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
