# Generated by Django 5.2.1 on 2026-03-19 09:59

import account.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("is_staff", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            managers=[
                ("objects", account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuthenticateToken",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("key_type", models.CharField(db_index=True, max_length=50)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("blacklisted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authenticate_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingInfo",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_infos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="account_use_email_553b8f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_staff"], name="account_use_is_acti_da44fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="account_use_date_jo_403b71_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", ""), _negated=True),
                name="user_email_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="authenticatetoken",
            index=models.Index(
                fields=["user", "expires_at"], name="account_aut_user_id_a89713_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticatetoken",
            index=models.Index(
                fields=["user", "blacklisted_at"], name="account_aut_user_id_3f7097_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticatetoken",
            index=models.Index(fields=["token"], name="account_aut_token_05b403_idx"),
        ),
        migrations.AddConstraint(
            model_name="authenticatetoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("token", ""), _negated=True),
                name="auth_token_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="shippinginfo",
            index=models.Index(
                fields=["user", "is_default"], name="account_shi_user_id_328c5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippinginfo",
            index=models.Index(
                fields=["user", "created_at"], name="account_shi_user_id_b7d884_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shippinginfo",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="shipping_info_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippinginfo",
            constraint=models.CheckConstraint(
                condition=models.Q(("phone", ""), _negated=True),
                name="shipping_info_phone_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippinginfo",
            constraint=models.CheckConstraint(
                condition=models.Q(("address", ""), _negated=True),
                name="shipping_info_address_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippinginfo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="unique_default_shipping_info_per_user",
            ),
        ),
    ]
