# Generated by Django 5.2.1 on 2025-12-20 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="identifier",
        ),
    ]
