# Generated by Django 5.2.1 on 2025-12-29 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed")],
                        max_length=10,
                    ),
                ),
                ("value", models.IntegerField()),
                ("start_time", models.DateField(blank=True, null=True)),
                ("end_time", models.DateField(blank=True, null=True)),
                ("max_usage", models.IntegerField(blank=True, null=True)),
                ("min_order_amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=50)),
                ("amount", models.PositiveIntegerField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("payment_date", models.DateField(auto_now_add=True)),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("provider_response", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("order_date", models.DateField()),
                ("receive_date", models.DateField(blank=True, null=True)),
                ("payment_method", models.CharField(max_length=50)),
                ("total_amount", models.IntegerField()),
                ("discount_amount", models.IntegerField(blank=True, null=True)),
                ("shipping_fee", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipping", "Shipping"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_fk_discount",
                        to="order.discount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_fk_payment",
                        to="order.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_fk_order",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_fk_product",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
